### ISSUE TITLE
Terraform Aqua provider is crashing when deploying many Aqua objects

### ISSUE THREAD

**Issue by ruzickap** [aquasecurity/terraform-provider-aquasec#137]
When I'm deploying large amount of object to Aqua SaaS [2022.04] using the Aqua provider - it is crashing. This may be related to the amount of API calls going to Aqua - but it is just my guess.
 
### Terraform Version

```bash
❯ terraform -v
Terraform v1.2.2
on darwin_amd64
+ provider registry.terraform.io/aquasecurity/aquasec v0.8.11
```

### Affected Resource(s)
- "any"

### Steps to Reproduce

I'm using this code to create enforcer groups in Aqua:

```hcl
terraform {
  backend "local" {
    path = "terraform.tfstate"
  }
  required_providers {
    aquasec = {
      version = "0.8.11"
      source  = "aquasecurity/aquasec"
    }
  }
}

provider "aquasec" {
  username = var.aquasec_username
  aqua_url = var.aquasec_url
  password = var.aquasec_password
}

variable "aquasec_username" {
  type        = string
  description = "Aqua Username"
}

variable "aquasec_password" {
  type        = string
  description = "Aqua Password"
}

variable "aquasec_url" {
  type        = string
  description = "Aqua URL"
}

resource "aquasec_permissions_sets" "test" {
    count = 100
    name = "test-aquasec_permissions_sets-${count.index}"
    description = "created from terraform"
    author    = "petr.ruzicka@gmail.com"
    ui_access = true
    is_super = false
    actions = [ ]
}
```

If I run `terraform apply / destroy` multiple times the terraform crashes: 

```text
$ terraform destroy
...
...
...
╷
│ Error: Request cancelled
│
│   with aquasec_permissions_sets.test[29],
│   on main.tf line 105, in resource "aquasec_permissions_sets" "test":
│  105: resource "aquasec_permissions_sets" "test" {
│
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│   with aquasec_permissions_sets.test[33],
│   on main.tf line 105, in resource "aquasec_permissions_sets" "test":
│  105: resource "aquasec_permissions_sets" "test" {
│
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

Stack trace from the terraform-provider-aquasec_v0.8.11 plugin:

fatal error: concurrent map writes

goroutine 722 [running]:
runtime.throw(0x18fc243, 0x15)
	runtime/panic.go:1117 +0x72 fp=0xc000725698 sp=0xc000725668 pc=0x1035d32
runtime.mapassign_faststr(0x1880e40, 0xc000389ef0, 0x18f60bb, 0xd, 0x286)
	runtime/map_faststr.go:211 +0x3f1 fp=0xc000725700 sp=0xc000725698 pc=0x10142f1
net/textproto.MIMEHeader.Set(...)
	net/textproto/header.go:22
net/http.Header.Set(...)
	net/http/header.go:37
github.com/parnurzeal/gorequest.(*SuperAgent).Set(...)
	github.com/parnurzeal/gorequest@v0.2.16/gorequest.go:371
github.com/aquasecurity/terraform-provider-aquasec/client.(*Client).GetPermissionsSet(0xc000262cb0, 0xc00077a6e0, 0x20, 0x17e2a60, 0xc000a00d00, 0x10b9401)
	github.com/aquasecurity/terraform-provider-aquasec/client/permission_sets.go:31 +0x165 fp=0xc000725858 sp=0xc000725700 pc=0x13225e5
github.com/aquasecurity/terraform-provider-aquasec/aquasec.resourcePermissionSetRead(0xc0003b1380, 0x18eab80, 0xc000262cb0, 0x1e4dc90, 0x1e1f440)
	github.com/aquasecurity/terraform-provider-aquasec/aquasec/resource_permission_set.go:102 +0x92 fp=0xc0007258a8 sp=0xc000725858 pc=0x1577b52
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0004bfbc0, 0x19f4678, 0xc000371500, 0xc0003b1380, 0x18eab80, 0xc000262cb0, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/helper/schema/resource.go:290 +0x88 fp=0xc000725918 sp=0xc0007258a8 pc=0x14d4468
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0004bfbc0, 0x19f4678, 0xc000371500, 0xc000436460, 0x18eab80, 0xc000262cb0, 0xc00000f2c0, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/helper/schema/resource.go:564 +0x1cb fp=0xc0007259c8 sp=0xc000725918 pc=0x14d634b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00040e168, 0x19f4678, 0xc000371500, 0xc000371600, 0xc000371500, 0x100b665, 0x188ba60)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/helper/schema/grpc_provider.go:575 +0x43b fp=0xc000725ae0 sp=0xc0007259c8 pc=0x14c925b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc00038b460, 0x19f4720, 0xc000371500, 0xc000108360, 0xc00038b460, 0xc0008e2750, 0xc000584ba0)
	github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:298 +0x105 fp=0xc000725b40 sp=0xc000725ae0 pc=0x1778f45
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x18b71c0, 0xc00038b460, 0x19f4720, 0xc0008e2750, 0xc0001082a0, 0x0, 0x19f4720, 0xc0008e2750, 0xc0008144b0, 0xe4)
	github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214 fp=0xc000725bb0 sp=0xc000725b40 pc=0x1770054
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00032cc40, 0x19fbeb8, 0xc000602f00, 0xc0008aac00, 0xc00039e570, 0x1e11eb0, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b fp=0xc000725e50 sp=0xc000725bb0 pc=0x171b3eb
google.golang.org/grpc.(*Server).handleStream(0xc00032cc40, 0x19fbeb8, 0xc000602f00, 0xc0008aac00, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c fp=0xc000725f68 sp=0xc000725e50 pc=0x171f5ac
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0001b8420, 0xc00032cc40, 0x19fbeb8, 0xc000602f00, 0xc0008aac00)
	google.golang.org/grpc@v1.32.0/server.go:859 +0xab fp=0xc000725fb8 sp=0xc000725f68 pc=0x172d56b
runtime.goexit()
	runtime/asm_amd64.s:1371 +0x1 fp=0xc000725fc0 sp=0xc000725fb8 pc=0x106c0c1
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

goroutine 1 [select]:
github.com/hashicorp/go-plugin.Serve(0xc000277e90)
	github.com/hashicorp/go-plugin@v1.4.0/server.go:468 +0x954
github.com/hashicorp/terraform-plugin-sdk/v2/plugin.Serve(0xc000402330)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/plugin/serve.go:82 +0x22d
main.main()
	github.com/aquasecurity/terraform-provider-aquasec/main.go:12 +0x45

goroutine 7 [select]:
github.com/hashicorp/go-plugin.(*gRPCBrokerServer).Recv(0xc00039e300, 0x0, 0x0, 0x0)
	github.com/hashicorp/go-plugin@v1.4.0/grpc_broker.go:121 +0x86
github.com/hashicorp/go-plugin.(*GRPCBroker).Run(0xc00018c0a0)
	github.com/hashicorp/go-plugin@v1.4.0/grpc_broker.go:411 +0x7a
created by github.com/hashicorp/go-plugin.(*GRPCServer).Init
	github.com/hashicorp/go-plugin@v1.4.0/grpc_server.go:85 +0x39c

goroutine 8 [IO wait]:
internal/poll.runtime_pollWait(0x572b710, 0x72, 0xffffffffffffffff)
	runtime/netpoll.go:227 +0x55
internal/poll.(*pollDesc).wait(0xc0001c0318, 0x72, 0x1001, 0x1000, 0xffffffffffffffff)
	internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0001c0300, 0xc000260000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:166 +0x1d5
os.(*File).read(...)
	os/file_posix.go:31
os.(*File).Read(0xc0001be0c0, 0xc000260000, 0x1000, 0x1000, 0x400, 0x17e5040, 0x175bc01)
	os/file.go:117 +0x77
bufio.(*Reader).Read(0xc00039df50, 0xc0001e6c00, 0x400, 0x400, 0x29, 0x0, 0x0)
	bufio/bufio.go:227 +0x222
github.com/hashicorp/go-plugin.copyChan(0x19ffda8, 0xc0004360e0, 0xc00018e480, 0x19e6240, 0xc0001be0c0)
	github.com/hashicorp/go-plugin@v1.4.0/grpc_stdio.go:181 +0xc5
created by github.com/hashicorp/go-plugin.newGRPCStdioServer
	github.com/hashicorp/go-plugin@v1.4.0/grpc_stdio.go:37 +0xb1

goroutine 9 [IO wait]:
internal/poll.runtime_pollWait(0x572b540, 0x72, 0xffffffffffffffff)
	runtime/netpoll.go:227 +0x55
internal/poll.(*pollDesc).wait(0xc0001c0438, 0x72, 0x1001, 0x1000, 0xffffffffffffffff)
	internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0001c0420, 0xc000264000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:166 +0x1d5
os.(*File).read(...)
	os/file_posix.go:31
os.(*File).Read(0xc0001be0e8, 0xc000264000, 0x1000, 0x1000, 0x400, 0x17e5040, 0x1)
	os/file.go:117 +0x77
bufio.(*Reader).Read(0xc000397750, 0xc0001e6800, 0x400, 0x400, 0x0, 0x0, 0x0)
	bufio/bufio.go:227 +0x222
github.com/hashicorp/go-plugin.copyChan(0x19ffda8, 0xc0004360e0, 0xc00018e4e0, 0x19e6240, 0xc0001be0e8)
	github.com/hashicorp/go-plugin@v1.4.0/grpc_stdio.go:181 +0xc5
created by github.com/hashicorp/go-plugin.newGRPCStdioServer
	github.com/hashicorp/go-plugin@v1.4.0/grpc_stdio.go:38 +0xfe

goroutine 36 [syscall]:
os/signal.signal_recv(0x0)
	runtime/sigqueue.go:165 +0x9d
os/signal.loop()
	os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	os/signal/signal.go:151 +0x45

Error: The terraform-provider-aquasec_v0.8.11 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

The workaround it to use `-parallelism=1` which makes Terraform less "aggressive".

-> Aqua provider should handle the "default" terraform parameters without specifying the `-parallelism=1`.

Thanks for looking at it...

**Comment by KoppulaRajender** [comment]
Hi @ruzickap, Thanks for raising this. we have checked internally and got to know that Aqua has an API rate limit of 30 requests per second. In order to increase this value please reach out to the Aqua Support Team. More details can find [here](https://docs.aquasec.com/docs/security-best-practices-api-usage#section-rate-limit-for-api-calls).

**Comment by ruzickap** [comment]
The API limits are understandable and it is a good practice to have them.

Actually the Aqua Terraform provider should not "crash" or break deployments when it reaches them (like it is shown above).

I would expect, that the TF provider can work with API limits (especially if they are known) and make (by default) 30 requests/sec without crashing...

**Comment by ruzickap** [comment]
Thanks for fixing it...
It is working fine now :-)
