### ISSUE TITLE
Error creating assurance policy

### ISSUE THREAD

**Issue by AquaOms** [aquasecurity/terraform-provider-aquasec#78]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
    aquasec = {
      version = "0.8.4"

### Affected Resource(s)
resource "aquasec_image_assurance_policy"

### Terraform Configuration Files
```hcl
    terraform {
      required_providers {
        aquasec = {
          version = "0.8.4"
          source  = "aquasecurity/aquasec"
        }
      }
    }

    provider "aquasec" {
      username = ""
      aqua_url = "https://*****.cloud.aquasec.com/"
      password = "PASSWORD_HERE"

      verify_tls = false
    }

    resource "aquasec_image_assurance_policy" "resource_name" {
      name               = "resource_name"
      assurance_type     = "image"  
      application_scopes = [
        "Global"
      ]

      auto_scan_enabled = true

      cves_white_list_enabled = true
      cves_white_list         = [
        "",
      ]

      ignored_risk_resources = [
        "",
      ]

      custom_severity_enabled = true
      cvss_severity           = "critical"

      scope {
        expression = "v1"

        variables {
          attribute = "image.name"
          name      = ""
          value     = "org/resource:*"
        }
      }
    }
```

### Debug Output
```
Stack trace from the terraform-provider-aquasec_v0.8.4 plugin:
```

### Panic Output
```
panic: interface conversion: interface {} is *schema.Set, not []interface {}

goroutine 120 [running]:
github.com/aquasecurity/terraform-provider-aquasec/aquasec.expandImageAssurancePolicy(0x140006e4280, 0x101079c2e)
	github.com/aquasecurity/terraform-provider-aquasec/aquasec/resource_image_assurance_policy.go:984 +0x3ce0
github.com/aquasecurity/terraform-provider-aquasec/aquasec.resourceImageAssurancePolicyCreate(0x140006e4280, 0x1012cb700, 0x1400042a240, 0xffffffffffffffff, 0x1400067f798)
	github.com/aquasecurity/terraform-provider-aquasec/aquasec/resource_image_assurance_policy.go:582 +0x84
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x140000bb980, 0x1012f6fb8, 0x14000045700, 0x140006e4280, 0x1012cb700, 0x1400042a240, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/helper/schema/resource.go:278 +0x5c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x140000bb980, 0x1012f6fb8, 0x14000045700, 0x140005b13b0, 0x140005b3c20, 0x1012cb700, 0x1400042a240, 0x0, 0x0, 0x0, ...)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/helper/schema/resource.go:396 +0x4e4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x140000900f0, 0x1012f6fb8, 0x14000045700, 0x14000423d10, 0x14000045700, 0x10129e280, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/helper/schema/grpc_provider.go:955 +0x6f8
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0x14000822040, 0x1012f7060, 0x14000045700, 0x140005b1180, 0x14000822040, 0x1010250c0, 0x101278be0)
	github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:332 +0x94
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x10129e280, 0x14000822040, 0x1012f7060, 0x140006ba960, 0x140008385a0, 0x0, 0x1012f7060, 0x140006ba960, 0x140001ce880, 0xcb4)
	github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x1c8
google.golang.org/grpc.(*Server).processUnaryRPC(0x140000b8380, 0x1012fea78, 0x14000603080, 0x140005e4400, 0x1400037e450, 0x1016f5be0, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0x3e8
google.golang.org/grpc.(*Server).handleStream(0x140000b8380, 0x1012fea78, 0x14000603080, 0x140005e4400, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xa50
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x14000514150, 0x140000b8380, 0x1012fea78, 0x14000603080, 0x140005e4400)
	google.golang.org/grpc@v1.32.0/server.go:859 +0x94
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x1f8
```

### Expected Behavior
Actually create assurance policy

### Actual Behavior
Error thrown, shown above.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. $ terraform init
1. $ terraform plan
1. $ terraform apply --auto-approve

[terraform.log](https://github.com/aquasecurity/terraform-provider-aquasec/files/8034906/terraform.log)

**Comment by ehardisty** [comment]
Recently merged PR #73 should fix this. There hasn't yet been a new release created from it, but the code has been fixed. @jerbia we should look to bump versions or push a repair to the existing version if possible to stop this happening to people.

**Comment by jerbia** [comment]
@ehardisty I've just published v0.8.5

**Comment by ehardisty** [comment]
@AquaOms Would you be able to confirm that with the newly released 0.8.5 version that this does in fact solve the issue? Thanks!

**Comment by semyonmor** [comment]
@AquaOms did you receive any answer from the customer?
Can we close the issue?

**Comment by semyonmor** [comment]
@AquaOms any update?
Can we close the issue?

**Comment by semyonmor** [comment]
@AquaOms 
We closing the issue.
If you still experience some issues with Assurance policy, feel free to contact us

**Comment by AquaOms** [comment]
Apologies for the very late response, the customer has succeeded to create the assurance policies. 
Thank you very much for your help.
