### ISSUE TITLE
Error creating image assurance policy maximum_score

### ISSUE THREAD

**Issue by devkSerge** [aquasecurity/terraform-provider-aquasec#83]
Hi there,

there seems to be an conversion error when using `maximum_score`?
https://github.com/aquasecurity/terraform-provider-aquasec/blob/main/aquasec/resource_image_assurance_policy.go#L869

```
terraform {
  required_version = ">= 0.13.7, < 2.0"
  required_providers {
    aquasec = {
      source  = "aquasecurity/aquasec"
      version = "0.8.5"
    }
  }
}

resource "aquasec_image_assurance_policy" "this" {
  application_scopes    = ["Global"]
  assurance_type        = "image"
  auto_scan_enabled     = true
  audit_on_failure      = true
  description           = "tf test image assurance CVE score greater then 8"
  name                  = "tf_test_image_assurance_CVE_score_greater_then_8"
  block_failed          = true
  fail_cicd             = true
  enabled               = true
  enforce               = true
  //maximum_score         = 8.0
  maximum_score         = 8
  maximum_score_enabled = true
  // custom_severity_enabled = true
  // cvss_severity           = "critical"
}
```

```
Error: rpc error: code = Unavailable desc = transport is closing


panic: interface conversion: interface {} is int, not float64
2022-02-14T14:07:40.935+0100 [DEBUG] plugin.terraform-provider-aquasec_v0.8.5: 
2022-02-14T14:07:40.935+0100 [DEBUG] plugin.terraform-provider-aquasec_v0.8.5: goroutine 27 [running]:
2022-02-14T14:07:40.935+0100 [DEBUG] plugin.terraform-provider-aquasec_v0.8.5: github.com/aquasecurity/terraform-provider-aquasec/aquasec.expandImageAssurancePolicy(0xc0000f6e00, 0xc0006152d0)
2022-02-14T14:07:40.935+0100 [DEBUG] plugin.terraform-provider-aquasec_v0.8.5:  github.com/aquasecurity/terraform-provider-aquasec/aquasec/resource_image_assurance_policy.go:869 +0x4db3
2022-02-14T14:07:40.935+0100 [DEBUG] plugin.terraform-provider-aquasec_v0.8.5: github.com/aquasecurity/terraform-provider-aquasec/aquasec.resourceImageAssurancePolicyUpdate(0xc0000f6e00, 0xc9b1a0, 0xc0006d0240, 0x0, 0xffffffffffffffff)
2022-02-14T14:07:40.935+0100 [DEBUG] plugin.terraform-provider-aquasec_v0.8.5:  github.com/aquasecurity/terraform-provider-aquasec/aquasec/resource_image_assurance_policy.go:610 +0x10f
2022-02-14T14:07:40.936+0100 [DEBUG] plugin.terraform-provider-aquasec_v0.8.5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc000333980, 0xda5358, 0xc0001a0340, 0xc0000f6e00, 0xc9b1a0, 0xc0006d0240, 0x0, 0x0, 0x0)
2022-02-14T14:07:40.936+0100 [DEBUG] plugin.terraform-provider-aquasec_v0.8.5:  github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/helper/schema/resource.go:302 +0x88
2022-02-14T14:07:40.936+0100 [DEBUG] plugin.terraform-provider-aquasec_v0.8.5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000333980, 0xda5358, 0xc0001a0340, 0xc0001b6690, 0xc0007166c0, 0xc9b1a0, 0xc0006d0240, 0x0, 0x0, 0x0, ...)
2022-02-14T14:07:40.936+0100 [DEBUG] plugin.terraform-provider-aquasec_v0.8.5:  github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/helper/schema/resource.go:404 +0x390
2022-02-14T14:07:40.936+0100 [DEBUG] plugin.terraform-provider-aquasec_v0.8.5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00030a0f0, 0xda5358, 0xc0001a0340, 0xc000318af0, 0xc0001a0340, 0xc6d9a0, 0xc00049e100)
2022-02-14T14:07:40.936+0100 [DEBUG] plugin.terraform-provider-aquasec_v0.8.5:  github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/helper/schema/grpc_provider.go:955 +0x8ef
2022-02-14T14:07:40.936+0100 [DEBUG] plugin.terraform-provider-aquasec_v0.8.5: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc000568040, 0xda5400, 0xc0001a0340, 0xc0005f6070, 0xc000568040, 0xc00049e1b0, 0xc0004adba0)
2022-02-14T14:07:40.936+0100 [DEBUG] plugin.terraform-provider-aquasec_v0.8.5:  github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:332 +0xb5
2022-02-14T14:07:40.936+0100 [DEBUG] plugin.terraform-provider-aquasec_v0.8.5: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0xc6d9a0, 0xc000568040, 0xda5400, 0xc00049e1b0, 0xc0002e8120, 0x0, 0xda5400, 0xc00049e1b0, 0xc00011b500, 0x13c9)
2022-02-14T14:07:40.936+0100 [DEBUG] plugin.terraform-provider-aquasec_v0.8.5:  github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
2022-02-14T14:07:40.936+0100 [DEBUG] plugin.terraform-provider-aquasec_v0.8.5: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003301c0, 0xdac958, 0xc0004c2900, 0xc0004a4000, 0xc000171620, 0x11b2c60, 0x0, 0x0, 0x0)
2022-02-14T14:07:40.936+0100 [DEBUG] plugin.terraform-provider-aquasec_v0.8.5:  google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
2022-02-14T14:07:40.936+0100 [DEBUG] plugin.terraform-provider-aquasec_v0.8.5: google.golang.org/grpc.(*Server).handleStream(0xc0003301c0, 0xdac958, 0xc0004c2900, 0xc0004a4000, 0x0)
2022-02-14T14:07:40.936+0100 [DEBUG] plugin.terraform-provider-aquasec_v0.8.5:  google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
2022-02-14T14:07:40.936+0100 [DEBUG] plugin.terraform-provider-aquasec_v0.8.5: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00028a1e0, 0xc0003301c0, 0xdac958, 0xc0004c2900, 0xc0004a4000)
2022-02-14T14:07:40.936+0100 [DEBUG] plugin.terraform-provider-aquasec_v0.8.5:  google.golang.org/grpc@v1.32.0/server.go:859 +0xab
2022-02-14T14:07:40.936+0100 [DEBUG] plugin.terraform-provider-aquasec_v0.8.5: created by google.golang.org/grpc.(*Server).serveStreams.func1
2022-02-14T14:07:40.936+0100 [DEBUG] plugin.terraform-provider-aquasec_v0.8.5:  google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
2022-02-14T14:07:40.938+0100 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2022-02-14T14:07:40.938+0100 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/aquasecurity/aquasec/0.8.5/linux_amd64/terraform-provider-aquasec_v0.8.5 pid=2306 error="exit status 2"
2022/02/14 14:07:40 [DEBUG] aquasec_image_assurance_policy.this: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
```
Thank you

**Comment by KoppulaRajender** [comment]
Hi @devkSerge, This is due to type conversion from float to int.
Maximum_score should be a float64 type.
Added fix to PR: https://github.com/aquasecurity/terraform-provider-aquasec/pull/85
